# This file is part of the partake project
# Copyright 2020-2023 Board of Regents of the University of Wisconsin System
# SPDX-License-Identifier: MIT

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args: ["--allow-multiple-documents"]
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.3
    hooks:
      - id: editorconfig-checker
        alias: ec
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.2
    hooks:
      - id: clang-format
  - repo: https://github.com/fsfe/reuse-tool
    rev: v2.1.0
    hooks:
      - id: reuse
        # See: https://github.com/fsfe/reuse-tool/issues/576
        args: ["--include-meson-subprojects", "lint"]
