# This file is part of the partake project
# Copyright 2020-2023 Board of Regents of the University of Wisconsin System
# SPDX-License-Identifier: MIT

common_incdir = include_directories('.')

common_sources = files([
    'posix.cpp',
    'proquint.cpp',
    'random.cpp',
    'win32.cpp',
])

subdir('tests')
